version: "3.8"

services:
  postgres_db:
    image: postgres
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default_database

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres_db
    ports:
      - 3002:8080
  
  flask_server:
    build: ./server
    depends_on:
      - postgres_db
    ports:
      - 3001:5000
    environment:
      DATABASE_URL: postgresql://admin:password@postgres_db:5432/default_database

  angular_client:
    build: 
      context: ./client
      args:
        API_BASE_URL: http://localhost:3001
    
    depends_on:
      - flask_server
    ports:
      - 3000:80
    

networks:
  default: 
    name: default_network